//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepoVKR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraduateBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GraduateBook()
        {
            this.GraduateWorkFile = new HashSet<GraduateWorkFile>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid StudentId { get; set; }
        public System.Guid ScienceDirectorId { get; set; }
        public System.Guid ReviewerId { get; set; }
        public string VKRName { get; set; }
        public string VKRNameEng { get; set; }
        public string ScienceDirectorInfo { get; set; }
        public string ReviewerInfo { get; set; }
        public string VKRAnnotation { get; set; }
        public string VKRAnnotationEng { get; set; }
    
        public virtual Reviewer Reviewer { get; set; }
        public virtual ScienceDirector ScienceDirector { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GraduateWorkFile> GraduateWorkFile { get; set; }
    }
}
