//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepoVKR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraduateWorkFile
    {
        public System.Guid Id { get; set; }
        public System.Guid GraduateBookId { get; set; }
        public System.Guid FileStorageId { get; set; }
        public string FileName { get; set; }
        public int FileSize { get; set; }
        public string FileHash { get; set; }
        public string FileExtention { get; set; }
        public string MimeType { get; set; }
        public bool IsMainFile { get; set; }
    
        public virtual GraduateBook GraduateBook { get; set; }
    }
}
