//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepoVKR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RepoVKREntities : DbContext
    {
        public RepoVKREntities()
            : base("name=RepoVKREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GraduateBook> GraduateBook { get; set; }
        public virtual DbSet<GraduateWorkFile> GraduateWorkFile { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Reviewer> Reviewer { get; set; }
        public virtual DbSet<ScienceDirector> ScienceDirector { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudyLevelNameMask> StudyLevelNameMask { get; set; }
    }
}
